#cloud-config


groups:

  - admingroup: [root,sys]

  - cloud-users

users:

  - default

  - name: Baptiste

    gecos: Baptiste lanlo

    primary_group: baptiste

    groups: admingroup

    lock_passwd: false

    passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChNZxIV4RRmGioerWj8KhWU4d+/mfX9x1RKHP/CRxfVUNm3wXZO7YDuSg2C8+3YLRhpiWU44LAYAo8l8SmrcYFE77sgc7aKotPkyaDb2Rg0pLsnyrenhse4Ql8wXI21LW61Y9Bvt739Xm41zC0CI13vAdA05M1Ksj07e3W09xGsRRrPFJL3Lx3aIrBhcOKfs4kowiwdh9+FEL1vqR5x+qX+e39zrWbNVbafOgVE1HrtCpxyB4bjcmz8LtthlpQ2HxOcxBq9hK96lUBvzF1eTSXlGHpHogvFcFihdbmSVMXZdc9BNEmEhmraALLitOYa+QhHWlvZcz6Vob3WzCz9PXD rsa-key-20220728 Baptiste@host

ssh_autorized_key : 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChNZxIV4RRmGioerWj8KhWU4d+/mfX9x1RKHP/CRxfVUNm3wXZO7YDuSg2C8+3YLRhpiWU44LAYAo8l8SmrcYFE77sgc7aKotPkyaDb2Rg0pLsnyrenhse4Ql8wXI21LW61Y9Bvt739Xm41zC0CI13vAdA05M1Ksj07e3W09xGsRRrPFJL3Lx3aIrBhcOKfs4kowiwdh9+FEL1vqR5x+qX+e39zrWbNVbafOgVE1HrtCpxyB4bjcmz8LtthlpQ2HxOcxBq9hK96lUBvzF1eTSXlGHpHogvFcFihdbmSVMXZdc9BNEmEhmraALLitOYa+QhHWlvZcz6Vob3WzCz9PXD rsa-key-20220728 Baptiste@host
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUYo7CSezpbchg1BX29KBkoA/Ebfhpvk6Dp9uuTMlgPgTrFm/XlnuB/f2BLZDavwtKJqq61xkGri/MSJD3pXrwQbMG/mRts6xLCrRkEICljFpOn14SwJuRWPRxY08Uk0xLQulozVw3lKAx5zimK4NbxGKpDWXFsVB3T16xJHE+w3iTzQaXxpIftUCWJwlpeQSiWq4ZBik2M+lLde0Mgch8iUG8qmev3hlJZvsd7WpxidsnYIP4W49SBG3Md35LWAV3jN/UQsDU1RCN32f1Z3HXiQxvPHJ+PinO4A3ZE3RZHY/qhzPNNcuc1jT9pEvG6rYSEXFfkoXTcro9V+jX1MaD
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAFjy502YGu/9ynT+GKUvGASthTm6GdBjWx+SeBgdT5k1aj0Vrp1cYrRrigf744XxHfy8WioKiK/MnnIaL+demOAN/rI6YHOYrLtMEoABoukwniO+hEWFhu7vBH4j8nMSLvCvaqDJzpa3MkzcUa4vN9VO6cl6XNjGpze0KBXN6UiSrFv7DDfasoEz+KcU1YBblzo/C9/2KGMovlgvOZMjNWKBjf+na99ebx/9iffL1A7QyRtW46Xc05gNPVEOCd1QkZcqUDPpmpkoCG0m7ZjMq9uCFrknKXo56NdBzq/YT13HME5mEA9h7buT7YFbkv6iylwjn5bB/oQsf/z+nUlTlxfTMRWUuKV63WG8cBpu4w5bOvhUYv3oDwwsGsLC+wi7+mYP8kSZTKaK67wp/BRSZBajmK0BYax0inQN+p6HE09a7678nFJLC0o8wYBZ/Oj1kIqdOETzvws/blU5tuUHGXHyxSqm5JbqY0rJOa3hPZTuaO5PQu63SZQz0Lkd286FNoZBTVzMC4bVqxegMV7ozgesLt0R0ZmWmzhxNKvxFgTw3PZEu7QPvxrLdSTSOdRazjHmz13pV7qdEKn4ACRiPzqAbZJqaE2L/2TewglaEs6zzRl79l+sUJrr8afz0C/oP0BsaV7ohQcNnlyMfab8rmlVitu5iSfV0V+ojB7bKyJX
package_update: True

packages:
  - wget
  - git




write_files:
  - path: /etc/systemd/system/gitea.service
    content: |
        [Unit]
        Description=Gitea (Git with a cup of tea)
        After=syslog.target
        After=network.target
        ###
        # Don't forget to add the database service dependencies
        ###
        #
        #Wants=mysql.service
        #After=mysql.service
        #
        #Wants=mariadb.service
        #After=mariadb.service
        #
        #Wants=postgresql.service
        #After=postgresql.service
        #
        #Wants=memcached.service
        #After=memcached.service
        #
        #Wants=redis.service
        #After=redis.service
        #
        ###
        # If using socket activation for main http/s
        ###
        #
        #After=gitea.main.socket
        #Requires=gitea.main.socket
        #
        ###
        # (You can also provide gitea an http fallback and/or ssh socket too)
        #
        # An example of /etc/systemd/system/gitea.main.socket
        ###
        ##
        ## [Unit]
        ## Description=Gitea Web Socket
        ## PartOf=gitea.service
        ##
        ## [Socket]
        ## Service=gitea.service
        ## ListenStream=<some_port>
        ## NoDelay=true
        ##
        ## [Install]
        ## WantedBy=sockets.target
        ##
        ###

        [Service]
        # Modify these two values and uncomment them if you have
        # repos with lots of files and get an HTTP error 500 because
        # of that
        ###
        #LimitMEMLOCK=infinity
        #LimitNOFILE=65535
        RestartSec=2s
        Type=simple
        User=git
        Group=git
        WorkingDirectory=/var/lib/gitea/
        # If using Unix socket: tells systemd to create the /run/gitea folder, which will contain the gitea.sock file
        # (manually creating /run/gitea doesn't work, because it would not persist across reboots)
        #RuntimeDirectory=gitea
        ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
        Restart=always
        Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
        # If you install Git to directory prefix other than default PATH (which happens
        # for example if you install other versions of Git side-to-side with
        # distribution version), uncomment below line and add that prefix to PATH
        # Don't forget to place git-lfs binary on the PATH below if you want to enable
        # Git LFS support
        #Environment=PATH=/path/to/git/bin:/bin:/sbin:/usr/bin:/usr/sbin
        # If you want to bind Gitea to a port below 1024, uncomment
        # the two values below, or use socket activation to pass Gitea its ports as above
        ###
        #CapabilityBoundingSet=CAP_NET_BIND_SERVICE
        #AmbientCapabilities=CAP_NET_BIND_SERVICE
        ###
        # In some cases, when using CapabilityBoundingSet and AmbientCapabilities option, you may want to
        # set the following value to false to allow capabilities to be applied on gitea process. The following
        # value if set to true sandboxes gitea service and prevent any processes from running with privileges
        # in the host user namespace.
        ###
        #PrivateUsers=false
        ###

        [Install]
        WantedBy=multi-user.target
 
runcmd:
  - [sudo, git, config, --global, user.name, "simplon-lanloBaptiste"]
  - [sudo, git, config, --global, user.email "simplonlanlobaptiste@gmail.com"]
  - [sudo, wget, "https://dl.gitea.io/gitea/1.16.7/gitea-1.16.7-linux-amd64", -O, /usr/local/bin/gitea ]
  - [sudo, chmod, +x, /usr/local/bin/gitea]
  - [sudo, adduser, --system, --shell, /bin/bash, --gecos, 'Git Version Control',--group, --disabled-password, --home, /home/git, git]
  - [sudo, mkdir, -p, /var/lib/gitea/custom]
  - [sudo, mkdir, -p, /var/lib/gitea/data]
  - [sudo, mkdir, -p, /var/lib/gitea/log]
  - [sudo, chown, -R, -v, "git:git", /var/lib/gitea]
  - [sudo, chmod, -R, "750", /var/lib/gitea]
  - [sudo, mkdir, -v, /etc/gitea]
  # - [sudo, git, clone, "https://github.com/simplon-lanloBaptiste/app.ini.git", /etc/gitea]
  - [sudo, chown, -R, "root:git", /etc/gitea]
  - [sudo, chmod, -R, "770", /etc/gitea]
  - [sudo, systemctl, enable, gitea]
  - [sudo, systemctl, start, gitea]
  - [sudo, apt, install, certbot, python3-certbot-apache]
  - [certbot, --apache]
  - [sudo, add-apt-repository ,"ppa:certbot/certbot"]
  - [sudo, certbot, certonly, --domain, b3g2eastus.eastus.cloudapp.azure.com, --email, baptistelanlo2@gmail.com, --agree-tos, --standalone]
  
